import { Iusuario } from '../interfaces/iusuario';

export const USUARIOS: Iusuario[] = [
  {
    id: 1,
    nombre: 'Juan',
    apellidos: 'García Pérez',
    email: 'juan@email.com',
    password: 'password123',
    rol: 'profesor',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Michael_Jordan_in_2014.jpg/220px-Michael_Jordan_in_2014.jpg',
    activo: true,
  },
  {
    id: 2,
    nombre: 'María',
    apellidos: 'López Rodríguez',
    email: 'maria@email.com',
    password: 'password456',
    rol: 'alumno',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Gal_Gadot_2018_cropped_retouched.jpg/220px-Gal_Gadot_2018_cropped_retouched.jpg',
    activo: true,
  },
  {
    id: 3,
    nombre: 'Carlos',
    apellidos: 'Martínez Sánchez',
    email: 'carlos@email.com',
    password: 'password789',
    rol: 'administrador',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Bill_Gates_-_2023_-_P062021-967902_%28cropped%29.jpg/300px-Bill_Gates_-_2023_-_P062021-967902_%28cropped%29.jpg',
    activo: true,
  },
  {
    id: 4,
    nombre: 'Ana',
    apellidos: 'Fernández Gómez',
    email: 'ana@email.com',
    password: 'passwordabc',
    rol: 'profesor',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Gal_Gadot_2018_cropped_retouched.jpg/220px-Gal_Gadot_2018_cropped_retouched.jpg',
    activo: true,
  },
  {
    id: 5,
    nombre: 'Pedro',
    apellidos: 'Ruiz Torres',
    email: 'pedro@email.com',
    password: 'passworddef',
    rol: 'alumno',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Michael_Jordan_in_2014.jpg/220px-Michael_Jordan_in_2014.jpg',
    activo: true,
  },
  {
    id: 6,
    nombre: 'Laura',
    apellidos: 'Gómez Sanz',
    email: 'laura@email.com',
    password: 'password101',
    rol: 'profesor',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Charlie_Sheen_March_2009.JPG/330px-Charlie_Sheen_March_2009.JPG',
    activo: true,
  },
  {
    id: 7,
    nombre: 'Miguel',
    apellidos: 'Hernández López',
    email: 'miguel@email.com',
    password: 'password202',
    rol: 'alumno',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Michael_Jordan_in_2014.jpg/220px-Michael_Jordan_in_2014.jpg',
    activo: true,
  },
  {
    id: 8,
    nombre: 'Elena',
    apellidos: 'Díaz Moreno',
    email: 'elena@email.com',
    password: 'password303',
    rol: 'profesor',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/THEY_ARE_ALL_DEAD_actress_Elena_Anaya_%28cropped%29_%28cropped%29.jpg/330px-THEY_ARE_ALL_DEAD_actress_Elena_Anaya_%28cropped%29_%28cropped%29.jpg',
    activo: true,
  },
  {
    id: 9,
    nombre: 'Pablo',
    apellidos: 'Jiménez Ortega',
    email: 'pablo@email.com',
    password: 'password404',
    rol: 'alumno',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Michael_Jordan_in_2014.jpg/220px-Michael_Jordan_in_2014.jpg',
    activo: true,
  },
  {
    id: 10,
    nombre: 'Sara',
    apellidos: 'Muñoz Vargas',
    email: 'sara@email.com',
    password: 'password505',
    rol: 'alumno',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Gal_Gadot_2018_cropped_retouched.jpg/220px-Gal_Gadot_2018_cropped_retouched.jpg',
    activo: true,
  },
  {
    id: 11,
    nombre: 'David',
    apellidos: 'Álvarez Castro',
    email: 'david@email.com',
    password: 'password606',
    rol: 'profesor',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/2023-11-16_Gala_de_los_Latin_Grammy%2C_22_%28David_Guetta%29.jpg/345px-2023-11-16_Gala_de_los_Latin_Grammy%2C_22_%28David_Guetta%29.jpg',
    activo: true,
  },
  {
    id: 12,
    nombre: 'Lucía',
    apellidos: 'Romero Navarro',
    email: 'lucia@email.com',
    password: 'password707',
    rol: 'alumno',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Gal_Gadot_2018_cropped_retouched.jpg/220px-Gal_Gadot_2018_cropped_retouched.jpg',
    activo: true,
  },
  {
    id: 13,
    nombre: 'Javier',
    apellidos: 'Sánchez Vidal',
    email: 'javier@email.com',
    password: 'password808',
    rol: 'profesor',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Javier_Santaolalla_conferencia_Divulgaci%C3%B3n_cient%C3%ADfica_y_Universidad_p%C3%BAblica5_%28cropped%29.png/330px-Javier_Santaolalla_conferencia_Divulgaci%C3%B3n_cient%C3%ADfica_y_Universidad_p%C3%BAblica5_%28cropped%29.png',
    activo: true,
  },
  {
    id: 14,
    nombre: 'Carmen',
    apellidos: 'Molina Reyes',
    email: 'carmen@email.com',
    password: 'password909',
    rol: 'alumno',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Gal_Gadot_2018_cropped_retouched.jpg/220px-Gal_Gadot_2018_cropped_retouched.jpg',
    activo: true,
  },
  {
    id: 15,
    nombre: 'Antonio',
    apellidos: 'Gutiérrez Ramos',
    email: 'antonio@email.com',
    password: 'password010',
    rol: 'administrador',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Antonio_Banderas-66031_%28cropped%29.jpg/375px-Antonio_Banderas-66031_%28cropped%29.jpg',
    activo: true,
  },
  {
    id: 16,
    nombre: 'Albert',
    apellidos: 'Einstein Koch',
    email: 'albert@email.com',
    password: 'password010',
    rol: 'profesor',
    foto: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Albert_Einstein_Head.jpg/220px-Albert_Einstein_Head.jpg',
    activo: true,
  },
];
