import { Iusuario } from '../interfaces/iusuario';

export const USUARIOS: Iusuario[] = [
  {
    id: 1,
    nombre: 'Juan',
    apellidos: 'García Pérez',
    email: 'juan@email.com',
    password: 'password123',
    rol: 'profesor',
    foto: 'juan.jpg',
    activo: true,
  },
  {
    id: 2,
    nombre: 'María',
    apellidos: 'López Rodríguez',
    email: 'maria@email.com',
    password: 'password456',
    rol: 'alumno',
    foto: 'maria.jpg',
    activo: true,
  },
  {
    id: 3,
    nombre: 'Carlos',
    apellidos: 'Martínez Sánchez',
    email: 'carlos@email.com',
    password: 'password789',
    rol: 'administrador',
    foto: 'carlos.jpg',
    activo: true,
  },
  {
    id: 4,
    nombre: 'Ana',
    apellidos: 'Fernández Gómez',
    email: 'ana@email.com',
    password: 'passwordabc',
    rol: 'profesor',
    foto: 'ana.jpg',
    activo: true,
  },
  {
    id: 5,
    nombre: 'Pedro',
    apellidos: 'Ruiz Torres',
    email: 'pedro@email.com',
    password: 'passworddef',
    rol: 'alumno',
    foto: 'pedro.jpg',
    activo: true,
  },
  {
    id: 6,
    nombre: 'Laura',
    apellidos: 'Gómez Sanz',
    email: 'laura@email.com',
    password: 'password101',
    rol: 'profesor',
    foto: 'laura.jpg',
    activo: true,
  },
  {
    id: 7,
    nombre: 'Miguel',
    apellidos: 'Hernández López',
    email: 'miguel@email.com',
    password: 'password202',
    rol: 'alumno',
    foto: 'miguel.jpg',
    activo: true,
  },
  {
    id: 8,
    nombre: 'Elena',
    apellidos: 'Díaz Moreno',
    email: 'elena@email.com',
    password: 'password303',
    rol: 'profesor',
    foto: 'elena.jpg',
    activo: true,
  },
  {
    id: 9,
    nombre: 'Pablo',
    apellidos: 'Jiménez Ortega',
    email: 'pablo@email.com',
    password: 'password404',
    rol: 'alumno',
    foto: 'pablo.jpg',
    activo: true,
  },
  {
    id: 10,
    nombre: 'Sara',
    apellidos: 'Muñoz Vargas',
    email: 'sara@email.com',
    password: 'password505',
    rol: 'alumno',
    foto: 'sara.jpg',
    activo: true,
  },
  {
    id: 11,
    nombre: 'David',
    apellidos: 'Álvarez Castro',
    email: 'david@email.com',
    password: 'password606',
    rol: 'profesor',
    foto: 'david.jpg',
    activo: true,
  },
  {
    id: 12,
    nombre: 'Lucía',
    apellidos: 'Romero Navarro',
    email: 'lucia@email.com',
    password: 'password707',
    rol: 'alumno',
    foto: 'lucia.jpg',
    activo: true,
  },
  {
    id: 13,
    nombre: 'Javier',
    apellidos: 'Sánchez Vidal',
    email: 'javier@email.com',
    password: 'password808',
    rol: 'profesor',
    foto: 'javier.jpg',
    activo: true,
  },
  {
    id: 14,
    nombre: 'Carmen',
    apellidos: 'Molina Reyes',
    email: 'carmen@email.com',
    password: 'password909',
    rol: 'alumno',
    foto: 'carmen.jpg',
    activo: true,
  },
  {
    id: 15,
    nombre: 'Antonio',
    apellidos: 'Gutiérrez Ramos',
    email: 'antonio@email.com',
    password: 'password010',
    rol: 'administrador',
    foto: 'antonio.jpg',
    activo: true,
  },
];
